# Generated by Django 5.1.15 on 2026-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_alter_webhookevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundevent',
            name='department',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='department_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='legal_risk',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='legal_risk_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='triage_latency_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='triage_source',
            field=models.CharField(blank=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='urgency_level',
            field=models.CharField(blank=True, default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='urgency_score',
            field=models.FloatField(default=1.0),
        ),
    ]
